#!/usr/bin/env bun

import { writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const outputPath = join(root, "DEPENDENCY_NOTICES.md");

type PackageManifest = {
  name?: unknown;
  version?: unknown;
  license?: unknown;
};

function licenseLabel(value: unknown, packageId: string): string {
  if (typeof value === "string" && value.trim()) return value.trim();
  if (Array.isArray(value)) {
    const values = value.filter(
      (entry): entry is string => typeof entry === "string" && !!entry.trim(),
    );
    if (values.length) return values.join(" OR ");
  }
  if (
    value &&
    typeof value === "object" &&
    "type" in value &&
    typeof value.type === "string" &&
    value.type.trim()
  ) {
    return value.type.trim();
  }
  throw new Error(`${packageId} has no declared licence`);
}

function escapeCell(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll("\n", " ");
}

export async function generateDependencyNotices(): Promise<string> {
  const packages = new Map<
    string,
    { name: string; version: string; license: string }
  >();
  const glob = new Bun.Glob("node_modules/.bun/*/node_modules/**/package.json");
  for await (const path of glob.scan({ cwd: root, onlyFiles: true })) {
    const manifest = (await Bun.file(
      join(root, path),
    ).json()) as PackageManifest;
    if (
      typeof manifest.name !== "string" ||
      typeof manifest.version !== "string"
    ) {
      continue;
    }
    const packageId = `${manifest.name}@${manifest.version}`;
    const license = licenseLabel(manifest.license, `${packageId} (${path})`);
    packages.set(packageId, {
      name: manifest.name,
      version: manifest.version,
      license,
    });
  }
  if (!packages.size) {
    throw new Error("no installed Bun packages found; run bun install first");
  }
  const rows = [...packages.values()].sort(
    (left, right) =>
      left.name.localeCompare(right.name) ||
      left.version.localeCompare(right.version),
  );
  return [
    "# Resolved JavaScript dependency notices",
    "",
    "Generated by `bun run notices:generate` from the complete pinned Bun install.",
    "This inventory includes build and verification tooling because the same lockfile",
    "resolves release builds. Package authors retain their own copyright and licence",
    "terms; the declared SPDX/value below is notice metadata, not a relicensing.",
    "",
    "| Package | Version | Declared licence |",
    "| --- | --- | --- |",
    ...rows.map(
      ({ name, version, license }) =>
        `| ${escapeCell(name)} | ${escapeCell(version)} | ${escapeCell(license)} |`,
    ),
    "",
  ].join("\n");
}

const generated = await generateDependencyNotices();
if (process.argv.includes("--check")) {
  const current = await Bun.file(outputPath)
    .text()
    .catch(() => "");
  if (current !== generated) {
    console.error(
      "DEPENDENCY_NOTICES.md is stale; run bun run notices:generate and commit it",
    );
    process.exit(1);
  }
  console.log("Dependency notices are current");
} else {
  await writeFile(outputPath, generated);
  console.log(`Wrote ${outputPath}`);
}
